sudo: required
services:
  - docker

before_install:
  - docker build -t vencerlanz/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true vencerlanz/react-test npm test

after_success:
  - docker build -t vencerlanz/mult-client ./client
  - docker build -t vencerlanz/multi-nginx ./nginx
  - docker build -t vencerlanz/multi-server ./server
  - docker build -t vencerlanz/multi-worker ./worker
  # Log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those image and push them to docker hub 
  - docker push vencerlanz/multi-client
  - docker push vencerlanz/multi-nginx
  - docker push vencerlanz/multi-server
  - docker push vencerlanz/multi-worker